import type { Locale, StackDetailCopy } from './types'

export const stackDetailByLocale: Record<Locale, StackDetailCopy> = {
  ko: {
    kicker: 'Stack Matrix',
    heading: '기술 스택 상세',
    description: '',
    backCta: '메인으로',
    columnSkill: '기술',
    columnCategory: '분야',
    columnProficiency: '숙련도',
    columnProjectUsed: '프로젝트에서 사용',
    columnPracticalUsed: '실무에서 사용해봄',
    columnInternals: '내부 구조를 뜯어봄',
    columnNote: '요약',
    yesLabel: '가능',
    noLabel: '아직',
    summaryProjectUsed: '프로젝트에서 사용',
    summaryPracticalUsed: '실무에서 사용',
    summaryInternals: '내부 구조 분석',
    items: [
      {
        icon: '🧠',
        imageSrc: 'https://api.iconify.design/lucide/bug.svg?color=%23ef4444',
        imageAlt: 'Malware Analysis',
        label: 'Window Malware Analysis',
        category: '보안',
        proficiency: '중',
        capability: {
          projectUsed: false,
          practicalUsed: false,
          internalsExplored: true,
        },
      },
      {
        icon: '🔬',
        imageSrc: 'https://api.iconify.design/lucide/binary.svg?color=%2394a3b8',
        imageAlt: 'Reverse Engineering',
        label: 'Window Program Reverse Engineering',
        category: '보안',
        proficiency: '중',
        capability: {
          projectUsed: false,
          practicalUsed: false,
          internalsExplored: true,
        },
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg',
        imageAlt: 'Python',
        label: 'Python',
        category: '언어',
        proficiency: '하',
        capability: {
          projectUsed: true,
          practicalUsed: false,
          internalsExplored: false,
        },
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg',
        imageAlt: 'Linux',
        label: 'Debian Linux',
        category: '인프라',
        proficiency: '중상',
        capability: {
          projectUsed: true,
          practicalUsed: false,
          internalsExplored: false,
        },
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg',
        imageAlt: 'Docker',
        label: 'Docker',
        category: '인프라',
        proficiency: '중상',
        capability: {
          projectUsed: true,
          practicalUsed: false,
          internalsExplored: true,
        },
      },
      {
        imageSrc:
          'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kubernetes/kubernetes-original.svg',
        imageAlt: 'Kubernetes',
        label: 'Kubernetes',
        category: '인프라',
        proficiency: '하',
        capability: {
          projectUsed: false,
          practicalUsed: false,
          internalsExplored: false,
        },
      },
      {
        imageSrc: 'https://cdn.simpleicons.org/proxmox/ef7a2d',
        imageAlt: 'Proxmox',
        label: 'Proxmox',
        category: '인프라',
        proficiency: '하',
        capability: {
          projectUsed: false,
          practicalUsed: false,
          internalsExplored: false,
        },
      },
      {
        icon: '☁️',
        imageSrc:
          'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original-wordmark.svg',
        imageAlt: 'AWS',
        label: 'AWS',
        category: '클라우드',
        proficiency: '중',
        capability: {
          projectUsed: true,
          practicalUsed: false,
          internalsExplored: false,
        },
      },
      {
        icon: '☁️',
        imageSrc: 'https://cdn.simpleicons.org/googlecloud/4285f4',
        imageAlt: 'GCP',
        label: 'GCP',
        category: '클라우드',
        proficiency: '중',
        capability: {
          projectUsed: true,
          practicalUsed: false,
          internalsExplored: false,
        },
      },
      {
        imageSrc:
          'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original-wordmark.svg',
        imageAlt: 'MySQL',
        label: 'MySQL',
        category: '데이터베이스',
        proficiency: '하',
        capability: {
          projectUsed: false,
          practicalUsed: false,
          internalsExplored: false,
        },
      },
      {
        imageSrc:
          'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg',
        imageAlt: 'Postgresql',
        label: 'Postgresql',
        category: '데이터베이스',
        proficiency: '하',
        capability: {
          projectUsed: true,
          practicalUsed: false,
          internalsExplored: false,
        },
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redis/redis-original.svg',
        imageAlt: 'Redis',
        label: 'Redis',
        category: '데이터베이스',
        proficiency: '하',
        capability: {
          projectUsed: true,
          practicalUsed: false,
          internalsExplored: false,
        },
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg',
        imageAlt: 'Spring Boot',
        label: 'Spring Boot',
        category: '백엔드',
        proficiency: '중',
        capability: {
          projectUsed: true,
          practicalUsed: false,
          internalsExplored: true,
        },
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/fastapi/fastapi-original.svg',
        imageAlt: 'FastAPI',
        label: 'FastAPI',
        category: '백엔드',
        proficiency: '하',
        capability: {
          projectUsed: true,
          practicalUsed: false,
          internalsExplored: true,
        },
      },
      {
        imageSrc:
          'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg',
        imageAlt: 'TypeScript',
        label: 'TypeScript',
        category: '언어',
        proficiency: '하',
        capability: {
          projectUsed: true,
          practicalUsed: false,
          internalsExplored: true,
        },
      },
      {
        imageSrc:
          'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg',
        imageAlt: 'JavaScript',
        label: 'JavaScript',
        category: '언어',
        proficiency: '하',
        capability: {
          projectUsed: false,
          practicalUsed: false,
          internalsExplored: true,
        },
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg',
        imageAlt: 'Java',
        label: 'Java',
        category: '언어',
        proficiency: '중',
        capability: {
          projectUsed: true,
          practicalUsed: false,
          internalsExplored: true,
        },
      },
      {
        imageSrc:
          'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg',
        imageAlt: 'C++',
        label: 'C++',
        category: '언어',
        proficiency: '상',
        capability: {
          projectUsed: false,
          practicalUsed: false,
          internalsExplored: true,
        },
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/c/c-original.svg',
        imageAlt: 'C',
        label: 'C',
        category: '언어',
        proficiency: '상',
        capability: {
          projectUsed: true,
          practicalUsed: false,
          internalsExplored: true,
        },
      },
      {
        imageSrc: 'https://api.iconify.design/lucide/cpu.svg?color=%239ca3af',
        imageAlt: 'Assembly',
        label: 'Assembly',
        category: '언어',
        proficiency: '상',
        capability: {
          projectUsed: false,
          practicalUsed: false,
          internalsExplored: true,
        },
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg',
        imageAlt: 'Vue 3',
        label: 'Vue 3',
        category: '웹 개발',
        proficiency: '하',
        capability: {
          projectUsed: true,
          practicalUsed: false,
          internalsExplored: true,
        },
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg',
        imageAlt: 'React',
        label: 'React',
        category: '웹 개발',
        proficiency: '중',
        capability: {
          projectUsed: false,
          practicalUsed: false,
          internalsExplored: true,
        },
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg',
        imageAlt: 'Next',
        label: 'Next',
        category: '웹 개발',
        proficiency: '중',
        capability: {
          projectUsed: true,
          practicalUsed: false,
          internalsExplored: true,
        },
      },
    ],
  },
  en: {
    kicker: 'Stack Matrix',
    heading: 'Tech Stack Details',
    description:
      'A matrix of each skill by project usage, practical workplace usage, and whether internals have been explored.',
    backCta: 'Back to main',
    columnSkill: 'Skill',
    columnCategory: 'Category',
    columnProficiency: 'Proficiency',
    columnProjectUsed: 'Used in projects',
    columnPracticalUsed: 'Used in practical work',
    columnInternals: 'Internals explored',
    columnNote: 'Notes',
    yesLabel: 'Yes',
    noLabel: 'No',
    summaryProjectUsed: 'Used in projects',
    summaryPracticalUsed: 'Used in practical work',
    summaryInternals: 'Internals explored',
    items: [
      {
        icon: '🧠',
        imageSrc: 'https://api.iconify.design/lucide/bug.svg?color=%23ef4444',
        imageAlt: 'Malware Analysis',
        label: 'Window Malware Analysis',
        category: 'Security',
        proficiency: 'Intermediate',
        capability: {
          projectUsed: false,
          practicalUsed: false,
          internalsExplored: true,
        },
      },
      {
        icon: '🔬',
        imageSrc: 'https://api.iconify.design/lucide/binary.svg?color=%2394a3b8',
        imageAlt: 'Reverse Engineering',
        label: 'Window Program Reverse Engineering',
        category: 'Security',
        proficiency: 'Intermediate',
        capability: {
          projectUsed: false,
          practicalUsed: false,
          internalsExplored: true,
        },
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg',
        imageAlt: 'Python',
        label: 'Python',
        category: 'Language',
        proficiency: 'Beginner',
        capability: {
          projectUsed: true,
          practicalUsed: false,
          internalsExplored: false,
        },
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg',
        imageAlt: 'Linux',
        label: 'Debian Linux',
        category: 'Infrastructure',
        proficiency: 'Upper-intermediate',
        capability: {
          projectUsed: true,
          practicalUsed: false,
          internalsExplored: false,
        },
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg',
        imageAlt: 'Docker',
        label: 'Docker',
        category: 'Infrastructure',
        proficiency: 'Upper-intermediate',
        capability: {
          projectUsed: true,
          practicalUsed: false,
          internalsExplored: true,
        },
      },
      {
        imageSrc:
          'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kubernetes/kubernetes-original.svg',
        imageAlt: 'Kubernetes',
        label: 'Kubernetes',
        category: 'Infrastructure',
        proficiency: 'Beginner',
        capability: {
          projectUsed: false,
          practicalUsed: false,
          internalsExplored: false,
        },
      },
      {
        imageSrc: 'https://cdn.simpleicons.org/proxmox/ef7a2d',
        imageAlt: 'Proxmox',
        label: 'Proxmox',
        category: 'Infrastructure',
        proficiency: 'Beginner',
        capability: {
          projectUsed: false,
          practicalUsed: false,
          internalsExplored: false,
        },
      },
      {
        icon: '☁️',
        imageSrc:
          'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original-wordmark.svg',
        imageAlt: 'AWS',
        label: 'AWS',
        category: 'Cloud',
        proficiency: 'Intermediate',
        capability: {
          projectUsed: true,
          practicalUsed: false,
          internalsExplored: false,
        },
      },
      {
        icon: '☁️',
        imageSrc: 'https://cdn.simpleicons.org/googlecloud/4285f4',
        imageAlt: 'GCP',
        label: 'GCP',
        category: 'Cloud',
        proficiency: 'Intermediate',
        capability: {
          projectUsed: true,
          practicalUsed: false,
          internalsExplored: false,
        },
      },
      {
        imageSrc:
          'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original-wordmark.svg',
        imageAlt: 'MySQL',
        label: 'MySQL',
        category: 'Database',
        proficiency: 'Beginner',
        capability: {
          projectUsed: false,
          practicalUsed: false,
          internalsExplored: false,
        },
      },
      {
        imageSrc:
          'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg',
        imageAlt: 'Postgresql',
        label: 'Postgresql',
        category: 'Database',
        proficiency: 'Beginner',
        capability: {
          projectUsed: true,
          practicalUsed: false,
          internalsExplored: false,
        },
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redis/redis-original.svg',
        imageAlt: 'Redis',
        label: 'Redis',
        category: 'Database',
        proficiency: 'Beginner',
        capability: {
          projectUsed: true,
          practicalUsed: false,
          internalsExplored: false,
        },
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg',
        imageAlt: 'Spring Boot',
        label: 'Spring Boot',
        category: 'Backend',
        proficiency: 'Intermediate',
        capability: {
          projectUsed: true,
          practicalUsed: false,
          internalsExplored: true,
        },
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/fastapi/fastapi-original.svg',
        imageAlt: 'FastAPI',
        label: 'FastAPI',
        category: 'Backend',
        proficiency: 'Beginner',
        capability: {
          projectUsed: true,
          practicalUsed: false,
          internalsExplored: true,
        },
      },
      {
        imageSrc:
          'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg',
        imageAlt: 'TypeScript',
        label: 'TypeScript',
        category: 'Language',
        proficiency: 'Beginner',
        capability: {
          projectUsed: true,
          practicalUsed: false,
          internalsExplored: true,
        },
      },
      {
        imageSrc:
          'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg',
        imageAlt: 'JavaScript',
        label: 'JavaScript',
        category: 'Language',
        proficiency: 'Beginner',
        capability: {
          projectUsed: false,
          practicalUsed: false,
          internalsExplored: true,
        },
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg',
        imageAlt: 'Java',
        label: 'Java',
        category: 'Language',
        proficiency: 'Intermediate',
        capability: {
          projectUsed: true,
          practicalUsed: false,
          internalsExplored: true,
        },
      },
      {
        imageSrc:
          'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg',
        imageAlt: 'C++',
        label: 'C++',
        category: 'Language',
        proficiency: 'Advanced',
        capability: {
          projectUsed: false,
          practicalUsed: false,
          internalsExplored: true,
        },
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/c/c-original.svg',
        imageAlt: 'C',
        label: 'C',
        category: 'Language',
        proficiency: 'Advanced',
        capability: {
          projectUsed: true,
          practicalUsed: false,
          internalsExplored: true,
        },
      },
      {
        imageSrc: 'https://api.iconify.design/lucide/cpu.svg?color=%239ca3af',
        imageAlt: 'Assembly',
        label: 'Assembly',
        category: 'Language',
        proficiency: 'Advanced',
        capability: {
          projectUsed: false,
          practicalUsed: false,
          internalsExplored: true,
        },
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg',
        imageAlt: 'Vue 3',
        label: 'Vue 3',
        category: 'Web Development',
        proficiency: 'Beginner',
        capability: {
          projectUsed: true,
          practicalUsed: false,
          internalsExplored: true,
        },
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg',
        imageAlt: 'React',
        label: 'React',
        category: 'Web Development',
        proficiency: 'Intermediate',
        capability: {
          projectUsed: false,
          practicalUsed: false,
          internalsExplored: true,
        },
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg',
        imageAlt: 'Next',
        label: 'Next',
        category: 'Web Development',
        proficiency: 'Intermediate',
        capability: {
          projectUsed: true,
          practicalUsed: false,
          internalsExplored: true,
        },
      },
    ],
  },
}
