import type { Locale, StackDetailCopy } from './types'

export const stackDetailByLocale: Record<Locale, StackDetailCopy> = {
  ko: {
    kicker: 'Stack Matrix',
    heading: '기술 스택 상세',
    description:
      '각 기술의 숙련도, 사용 경험, 프로젝트 경험, 실무 투입 가능 여부를 한눈에 볼 수 있도록 정리했습니다.',
    backCta: '메인으로',
    columnSkill: '기술',
    columnCategory: '분야',
    columnProficiency: '숙련도',
    columnUsedOnce: '한 번 이상 사용',
    columnProject: '프로젝트 경험',
    columnReady: '실무 즉시 투입',
    columnNote: '요약',
    yesLabel: '가능',
    noLabel: '아직',
    summaryUsedOnce: '사용 경험',
    summaryProject: '프로젝트 경험',
    summaryReady: '실무 투입 가능',
    items: [
      {
        icon: '🧠',
        label: 'Malware Analysis',
        category: '보안 분석',
        proficiency: '상',
        capability: {
          usedOnce: true,
          projectExperience: true,
          productionReady: true,
        },
        note: '정적/동적 분석과 대응 리포트 작성 가능',
      },
      {
        icon: '🔬',
        label: 'Reverse Engineering',
        category: '보안 분석',
        proficiency: '상',
        capability: {
          usedOnce: true,
          projectExperience: true,
          productionReady: true,
        },
        note: '코드 흐름 복원과 취약 지점 추적 가능',
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg',
        imageAlt: 'Python',
        label: 'Python',
        category: '자동화/개발',
        proficiency: '중상',
        capability: {
          usedOnce: true,
          projectExperience: true,
          productionReady: true,
        },
        note: '분석 자동화 스크립트와 내부 도구 구현',
      },
      {
        icon: '🧩',
        label: 'Ghidra',
        category: '리버싱 도구',
        proficiency: '상',
        capability: {
          usedOnce: true,
          projectExperience: true,
          productionReady: true,
        },
        note: '디컴파일 기반 구조 파악 및 시그니처 분석',
      },
      {
        icon: '🧰',
        label: 'IDA Pro',
        category: '리버싱 도구',
        proficiency: '중상',
        capability: {
          usedOnce: true,
          projectExperience: true,
          productionReady: true,
        },
        note: '함수 단위 추적과 패치 포인트 식별',
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg',
        imageAlt: 'Linux',
        label: 'Linux',
        category: '인프라/운영',
        proficiency: '중상',
        capability: {
          usedOnce: true,
          projectExperience: true,
          productionReady: true,
        },
        note: '운영 환경 점검과 트러블슈팅 수행',
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg',
        imageAlt: 'Docker',
        label: 'Docker',
        category: '배포/환경',
        proficiency: '중',
        capability: {
          usedOnce: true,
          projectExperience: true,
          productionReady: true,
        },
        note: '개발/배포 환경 컨테이너화 구성',
      },
      {
        icon: '☁️',
        label: 'AWS',
        category: '클라우드',
        proficiency: '중',
        capability: {
          usedOnce: true,
          projectExperience: true,
          productionReady: false,
        },
        note: '기본 서비스 구성 경험, 심화 운영은 학습 중',
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original-wordmark.svg',
        imageAlt: 'MySQL',
        label: 'MySQL',
        category: '데이터베이스',
        proficiency: '중',
        capability: {
          usedOnce: true,
          projectExperience: true,
          productionReady: true,
        },
        note: '기본 설계/쿼리 최적화 및 운영 경험',
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg',
        imageAlt: 'Spring Boot',
        label: 'Spring Boot',
        category: '백엔드',
        proficiency: '중',
        capability: {
          usedOnce: true,
          projectExperience: false,
          productionReady: false,
        },
        note: '기본 API 구성 및 학습 프로젝트 중심 경험',
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg',
        imageAlt: 'TypeScript',
        label: 'TypeScript',
        category: '웹 개발',
        proficiency: '중상',
        capability: {
          usedOnce: true,
          projectExperience: true,
          productionReady: true,
        },
        note: 'Vue 기반 화면/상태 로직 구현 가능',
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg',
        imageAlt: 'Vue 3',
        label: 'Vue 3',
        category: '웹 개발',
        proficiency: '중상',
        capability: {
          usedOnce: true,
          projectExperience: true,
          productionReady: true,
        },
        note: '컴포넌트 구조화와 반응형 UI 구축 경험',
      },
    ],
  },
  en: {
    kicker: 'Stack Matrix',
    heading: 'Tech Stack Details',
    description:
      'A compact matrix of each skill with proficiency, first-use exposure, project history, and production readiness.',
    backCta: 'Back to main',
    columnSkill: 'Skill',
    columnCategory: 'Category',
    columnProficiency: 'Proficiency',
    columnUsedOnce: 'Used at least once',
    columnProject: 'Project experience',
    columnReady: 'Production ready',
    columnNote: 'Notes',
    yesLabel: 'Yes',
    noLabel: 'No',
    summaryUsedOnce: 'Used at least once',
    summaryProject: 'Project experience',
    summaryReady: 'Production ready',
    items: [
      {
        icon: '🧠',
        label: 'Malware Analysis',
        category: 'Security Analysis',
        proficiency: 'Advanced',
        capability: {
          usedOnce: true,
          projectExperience: true,
          productionReady: true,
        },
        note: 'Static/dynamic analysis and incident report delivery',
      },
      {
        icon: '🔬',
        label: 'Reverse Engineering',
        category: 'Security Analysis',
        proficiency: 'Advanced',
        capability: {
          usedOnce: true,
          projectExperience: true,
          productionReady: true,
        },
        note: 'Control-flow reconstruction and weak-point tracing',
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg',
        imageAlt: 'Python',
        label: 'Python',
        category: 'Automation/Development',
        proficiency: 'Upper-intermediate',
        capability: {
          usedOnce: true,
          projectExperience: true,
          productionReady: true,
        },
        note: 'Automation scripts and internal tooling',
      },
      {
        icon: '🧩',
        label: 'Ghidra',
        category: 'Reversing Tooling',
        proficiency: 'Advanced',
        capability: {
          usedOnce: true,
          projectExperience: true,
          productionReady: true,
        },
        note: 'Decompiler-driven structure and signature analysis',
      },
      {
        icon: '🧰',
        label: 'IDA Pro',
        category: 'Reversing Tooling',
        proficiency: 'Upper-intermediate',
        capability: {
          usedOnce: true,
          projectExperience: true,
          productionReady: true,
        },
        note: 'Function-level tracing and patch-point review',
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg',
        imageAlt: 'Linux',
        label: 'Linux',
        category: 'Infra/Ops',
        proficiency: 'Upper-intermediate',
        capability: {
          usedOnce: true,
          projectExperience: true,
          productionReady: true,
        },
        note: 'Operational troubleshooting and security checks',
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg',
        imageAlt: 'Docker',
        label: 'Docker',
        category: 'Deployment/Environment',
        proficiency: 'Intermediate',
        capability: {
          usedOnce: true,
          projectExperience: true,
          productionReady: true,
        },
        note: 'Containerized setup for development and deployment',
      },
      {
        icon: '☁️',
        label: 'AWS',
        category: 'Cloud',
        proficiency: 'Intermediate',
        capability: {
          usedOnce: true,
          projectExperience: true,
          productionReady: false,
        },
        note: 'Core service usage done, deeper operations in progress',
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original-wordmark.svg',
        imageAlt: 'MySQL',
        label: 'MySQL',
        category: 'Database',
        proficiency: 'Intermediate',
        capability: {
          usedOnce: true,
          projectExperience: true,
          productionReady: true,
        },
        note: 'Schema/query basics and operational usage',
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg',
        imageAlt: 'Spring Boot',
        label: 'Spring Boot',
        category: 'Backend',
        proficiency: 'Intermediate',
        capability: {
          usedOnce: true,
          projectExperience: false,
          productionReady: false,
        },
        note: 'API baseline and learning-focused implementation',
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg',
        imageAlt: 'TypeScript',
        label: 'TypeScript',
        category: 'Web Development',
        proficiency: 'Upper-intermediate',
        capability: {
          usedOnce: true,
          projectExperience: true,
          productionReady: true,
        },
        note: 'Typed UI/state logic with Vue',
      },
      {
        imageSrc: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg',
        imageAlt: 'Vue 3',
        label: 'Vue 3',
        category: 'Web Development',
        proficiency: 'Upper-intermediate',
        capability: {
          usedOnce: true,
          projectExperience: true,
          productionReady: true,
        },
        note: 'Component architecture and responsive UI delivery',
      },
    ],
  },
}
