FROM node:22-alpine

WORKDIR /app

COPY server ./server
COPY src/entities/profile/model/profileShowcase.ts ./src/entities/profile/model/profileShowcase.ts
COPY src/entities/project/model/works.ts ./src/entities/project/model/works.ts

EXPOSE 8080

CMD ["node", "server/index.js"]
